### ISSUE TITLE
2015년 11월 28일 스터디

### ISSUE THREAD

**Issue by norux** [iamroot12D/linux#15]

**Comment by norux** [comment]
intptr_t 에 대한 설명: http://seoulforest.tistory.com/4

**Comment by norux** [comment]
https://msdn.microsoft.com/ko-kr/library/34h23df8.aspx

**Comment by fehead** [comment]
uintptr_t 한글 설명 : http://pr0x1ma.com/archives/46

**Comment by minidump** [comment]
<img width="591" alt="ansi c" src="https://cloud.githubusercontent.com/assets/1694778/11451724/6aa41d98-9613-11e5-9cb7-c488fc084c9f.PNG">
결국 ANSI C표준을 따르기 위해서 (char *)로 바로 바꾸지 않고 (uintptr_t)로 먼저 변환해준게 아닐까요?

```
         namep = (char *)(uintptr_t)fdt_get_name(fdt, nodeoffset, &oldlen);  
```

**Comment by norux** [comment]
(void*)(uintptr_t) 추가한 사람의 코멘트: http://lists.denx.de/pipermail/u-boot/2008-August/039070.html

기존에 (void*)로만 되어있었는데, (uintptr_t)를 추가한사람이 있습니다.
그사람이 추가한 이유를 남겨놨습니다.

**Comment by fehead** [comment]
컴파일러가 const 속성을  제거 할때 warnings 이 나올수 있는데.
이를 없애기 위해 uintptr_t 캐스팅을 한번 더 했다 라는것이 되겠네요.

**Comment by minidump** [comment]
fdt 헤더 안에는 이미 친절한 주석이 담겨있었어요;; https://github.com/iamroot12D/linux/blob/master/scripts/dtc/libfdt/libfdt.h

**Comment by fehead** [comment]
와 정말 헤더안에 자세한 주석들이 있군요.
